name: Docker Compose Actions Workflow
on:
  push:
    branches:
      - ci-test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
